### ISSUE TITLE
Logo/Icon for chrome extension

### ISSUE THREAD

**Issue by jbeguna04** [DoctorLai/JobTools#2]
Hello dear Project Owner, I would like to propose logo designs for your extension in chrome. Allow me to present my design to you. Hope it helps
![image](https://user-images.githubusercontent.com/35353768/38606215-fec86612-3da7-11e8-8d38-8cb74d942207.png)
![image](https://user-images.githubusercontent.com/35353768/38606345-524e8f28-3da8-11e8-8d2f-46f02f542126.png)
![sdvgerhb gn](https://user-images.githubusercontent.com/35353768/38613807-9ecfeee0-3dbd-11e8-873a-44f7e3cb1c69.png)

Thank You!

**Comment by DoctorLai** [comment]
Thanks for your LOGO, however, i have already have one.
